from .base import BaseWeightedLoss
from .cross_entropy_loss import CrossEntropyLoss
#from .Class_Specific_Contrastive_Loss import Class_Specific_Contrastive_Loss
from .proto_hard_triplet_loss import ProtoHardTripletLoss
